services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Unsafe_password__For_testing_purposes_only__Change_on_production"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-blob
    command: >
      azurite-blob
      --blobHost 0.0.0.0
      --blobPort 10000
    ports:
      - "10000:10000"
    volumes:
      - azurite_blob_data:/data
    restart: unless-stopped
    networks:
      - azurite-net

volumes:
  mssql-data:
  azurite_blob_data:
    
networks:
  azurite-net:
    driver: bridge