// <auto-generated />
using System;
using FileFlow.Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileFlow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileFlow.Application.Database.Entities.FileExtensionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Extension")
                        .IsUnique();

                    b.ToTable("FileExtensionCategory");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Category = 0,
                            Extension = ".doc"
                        },
                        new
                        {
                            Id = -2,
                            Category = 0,
                            Extension = ".docx"
                        },
                        new
                        {
                            Id = -3,
                            Category = 0,
                            Extension = ".pdf"
                        },
                        new
                        {
                            Id = -4,
                            Category = 0,
                            Extension = ".txt"
                        },
                        new
                        {
                            Id = -5,
                            Category = 0,
                            Extension = ".rtf"
                        },
                        new
                        {
                            Id = -6,
                            Category = 0,
                            Extension = ".odt"
                        },
                        new
                        {
                            Id = -7,
                            Category = 0,
                            Extension = ".xls"
                        },
                        new
                        {
                            Id = -8,
                            Category = 0,
                            Extension = ".xlsx"
                        },
                        new
                        {
                            Id = -9,
                            Category = 0,
                            Extension = ".csv"
                        },
                        new
                        {
                            Id = -10,
                            Category = 0,
                            Extension = ".ppt"
                        },
                        new
                        {
                            Id = -11,
                            Category = 0,
                            Extension = ".pptx"
                        },
                        new
                        {
                            Id = -12,
                            Category = 0,
                            Extension = ".md"
                        },
                        new
                        {
                            Id = -13,
                            Category = 0,
                            Extension = ".json"
                        },
                        new
                        {
                            Id = -14,
                            Category = 0,
                            Extension = ".xml"
                        },
                        new
                        {
                            Id = -15,
                            Category = 0,
                            Extension = ".yaml"
                        },
                        new
                        {
                            Id = -16,
                            Category = 0,
                            Extension = ".yml"
                        },
                        new
                        {
                            Id = -17,
                            Category = 0,
                            Extension = ".log"
                        },
                        new
                        {
                            Id = -18,
                            Category = 1,
                            Extension = ".jpg"
                        },
                        new
                        {
                            Id = -19,
                            Category = 1,
                            Extension = ".jpeg"
                        },
                        new
                        {
                            Id = -20,
                            Category = 1,
                            Extension = ".png"
                        },
                        new
                        {
                            Id = -21,
                            Category = 1,
                            Extension = ".gif"
                        },
                        new
                        {
                            Id = -22,
                            Category = 1,
                            Extension = ".bmp"
                        },
                        new
                        {
                            Id = -23,
                            Category = 1,
                            Extension = ".webp"
                        },
                        new
                        {
                            Id = -24,
                            Category = 1,
                            Extension = ".tiff"
                        },
                        new
                        {
                            Id = -25,
                            Category = 1,
                            Extension = ".tif"
                        },
                        new
                        {
                            Id = -26,
                            Category = 1,
                            Extension = ".svg"
                        },
                        new
                        {
                            Id = -27,
                            Category = 1,
                            Extension = ".heic"
                        },
                        new
                        {
                            Id = -28,
                            Category = 1,
                            Extension = ".ico"
                        },
                        new
                        {
                            Id = -29,
                            Category = 1,
                            Extension = ".raw"
                        },
                        new
                        {
                            Id = -30,
                            Category = 1,
                            Extension = ".psd"
                        },
                        new
                        {
                            Id = -31,
                            Category = 2,
                            Extension = ".mp4"
                        },
                        new
                        {
                            Id = -32,
                            Category = 2,
                            Extension = ".mkv"
                        },
                        new
                        {
                            Id = -33,
                            Category = 2,
                            Extension = ".mov"
                        },
                        new
                        {
                            Id = -34,
                            Category = 2,
                            Extension = ".avi"
                        },
                        new
                        {
                            Id = -35,
                            Category = 2,
                            Extension = ".wmv"
                        },
                        new
                        {
                            Id = -36,
                            Category = 2,
                            Extension = ".flv"
                        },
                        new
                        {
                            Id = -37,
                            Category = 2,
                            Extension = ".webm"
                        },
                        new
                        {
                            Id = -38,
                            Category = 2,
                            Extension = ".mpeg"
                        },
                        new
                        {
                            Id = -39,
                            Category = 2,
                            Extension = ".mpg"
                        },
                        new
                        {
                            Id = -40,
                            Category = 2,
                            Extension = ".3gp"
                        },
                        new
                        {
                            Id = -41,
                            Category = 2,
                            Extension = ".m4v"
                        });
                });

            modelBuilder.Entity("FileFlow.Application.Database.Entities.FileFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileCategory")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsInTrash")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IsInTrash");

                    b.HasIndex("IsStarred");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("FileFolders");
                });

            modelBuilder.Entity("FileFlow.Application.Database.Entities.UserStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Documents")
                        .HasColumnType("int");

                    b.Property<int>("Images")
                        .HasColumnType("int");

                    b.Property<int>("MaxSpace")
                        .HasColumnType("int");

                    b.Property<int>("Other")
                        .HasColumnType("int");

                    b.Property<int>("UsedSpace")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Videos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStorages");
                });
#pragma warning restore 612, 618
        }
    }
}
